import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, "schema.sql");
const target = resolve(root, "supabase/migrations/20260706000000_driftguard.sql");

await mkdir(dirname(target), { recursive: true });
const schema = await readFile(source, "utf8");
await writeFile(
  target,
  `-- GENERATED MIRROR OF /schema.sql. Do not edit this file directly.\n${schema}`,
  "utf8",
);
console.log("Synced schema.sql to the deployable Supabase migration.");
