export const BRANCH = {
  id: 'first60',
  product: 'TraceCrumb',
  productDescriptor: 'First Theory Check',
  kicker: 'For SRE, platform, and incident-response teams',
  tagline: 'Test the next move before the incident absorbs more time',
  headline: 'Before you restart, roll back, or escalate, check whether the first theory actually fits.',
  subheadline: 'Give TraceCrumb the redacted incident state, the theory your team is about to act on, and the evidence behind it. You get the strongest mismatch, one credible alternative, and the cheapest decisive check.',
  promise: 'Preserve the original theory, challenge it independently, record the next move, and close the loop with the eventual outcome.',
  benefitHook: 'TraceCrumb reviews only the redacted record you submit. It never connects to production, executes commands, or presents a hypothesis as root cause.',
  pain: 'During an incident, the first plausible explanation can become the plan before anyone records what contradicts it or what should force a switch.',
  loss: 'The team can spend the most expensive minutes of the incident following momentum instead of discriminating evidence.',
  userReturn: [
    'The strongest signal that does not fit the current theory',
    'A credible alternative explanation, clearly labeled as a hypothesis',
    'The cheapest observable check that can change the next action',
  ],
  nonGoals: [
    'No production-system access',
    'No autonomous remediation',
    'No root-cause claim',
    'No responder scoring',
    'No telemetry replacement',
  ],
  landing: {
    problemTitle: 'The first plausible theory becomes the plan.',
    problemBody: 'Rollback, restart, or escalation can begin before the team records the contradicting signal or the condition that should force a change.',
    solutionTitle: 'Save the theory before seeing the challenge.',
    solutionBody: 'TraceCrumb locks the original branch, then stress-tests only the evidence you supplied so the reasoning cannot be rewritten after the fact.',
    proofTitle: 'Leave with one decision-changing check.',
    proofBody: 'The result is an exportable record linking the original theory, contradiction, falsification check, chosen action, and eventual outcome.',
    ctaPrimary: 'Run a real check',
    ctaSecondary: 'See a worked example',
    validationCta: 'Start 10-run validation',
    auditCta: 'Request a founder-run audit',
  },
};
